services:
  landing-page:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: colifast-landing
    ports:
      - "4200:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
