server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Gérer le routage d'Angular (redirection vers index.html pour les routes inconnues de Nginx)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optionnel: Cache pour les assets statiques
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
